// Estados: NUEVO, ESPERANDO_MEMORIA, LISTO, EJECUTANDO, BLOQUEADO, TERMINADO
export type EstadoProceso =
  | "NUEVO"
  | "ESPERANDO_MEMORIA"
  | "LISTO"
  | "EJECUTANDO"
  | "BLOQUEADO"
  | "TERMINADO";
